name: Bump analyzers

on:
  schedule:
    - cron: "0 0 1,5,15,25 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.SIDER_INTERNAL_BOT_APP_ID }}
          private_key: ${{ secrets.SIDER_INTERNAL_BOT_PRIVATE_KEY }}
      - run: |
          bundle exec rake bump:analyzers
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GITHUB_AUTHOR_NAME: GitHub Actions
          GITHUB_AUTHOR_EMAIL: actions@github.com
